export enum TrainingSessionActionTypes {
  INIT_LOAD_TRAININGS_SUCCESS = "INIT_LOAD_TRAININGS_SUCCESS",
  INIT_LOAD_TRAININGS_FAIL = "INIT_LOAD_TRAININGS_FAIL",
  CREATE_TRAINING = "CREATE_TRAINING",
  CREATE_TRAINING_SUCCESS = "CREATE_TRAINING_SUCCESS",
  CREATE_TRAINING_FAIL = "CREATE_TRAINING_FAIL",
}
